import Header from "@/components/common/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className="grid max-h-screen place-items-center">
        <Header />
        {children}
      </body>
    </html>
  );
}
